package com.example.uumemory.entity;

import java.io.Serializable;
import java.util.Date;

public class Relics implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.id
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.uid
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.gmt_create
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.gmt_modified
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.character_id
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Long characterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.group_type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private String groupType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.main_type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private String mainType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.main_value
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double mainValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.max_health
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double maxHealth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.min_health
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double minHealth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.max_attack
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double maxAttack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.min_attack
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double minAttack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.max_defense
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double maxDefense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.min_defense
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double minDefense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.critical_strike_rate
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double criticalStrikeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.critical_strike_damage
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double criticalStrikeDamage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.proficients
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double proficients;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.charging_rate
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private Double chargingRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relics.ext
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relics
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.id
     *
     * @return the value of relics.id
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.id
     *
     * @param id the value for relics.id
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.uid
     *
     * @return the value of relics.uid
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.uid
     *
     * @param uid the value for relics.uid
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.gmt_create
     *
     * @return the value of relics.gmt_create
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.gmt_create
     *
     * @param gmtCreate the value for relics.gmt_create
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.gmt_modified
     *
     * @return the value of relics.gmt_modified
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.gmt_modified
     *
     * @param gmtModified the value for relics.gmt_modified
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.character_id
     *
     * @return the value of relics.character_id
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Long getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.character_id
     *
     * @param characterId the value for relics.character_id
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setCharacterId(Long characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.type
     *
     * @return the value of relics.type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.type
     *
     * @param type the value for relics.type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.group_type
     *
     * @return the value of relics.group_type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.group_type
     *
     * @param groupType the value for relics.group_type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.main_type
     *
     * @return the value of relics.main_type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public String getMainType() {
        return mainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.main_type
     *
     * @param mainType the value for relics.main_type
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMainType(String mainType) {
        this.mainType = mainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.main_value
     *
     * @return the value of relics.main_value
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getMainValue() {
        return mainValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.main_value
     *
     * @param mainValue the value for relics.main_value
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMainValue(Double mainValue) {
        this.mainValue = mainValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.max_health
     *
     * @return the value of relics.max_health
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getMaxHealth() {
        return maxHealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.max_health
     *
     * @param maxHealth the value for relics.max_health
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMaxHealth(Double maxHealth) {
        this.maxHealth = maxHealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.min_health
     *
     * @return the value of relics.min_health
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getMinHealth() {
        return minHealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.min_health
     *
     * @param minHealth the value for relics.min_health
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMinHealth(Double minHealth) {
        this.minHealth = minHealth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.max_attack
     *
     * @return the value of relics.max_attack
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getMaxAttack() {
        return maxAttack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.max_attack
     *
     * @param maxAttack the value for relics.max_attack
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMaxAttack(Double maxAttack) {
        this.maxAttack = maxAttack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.min_attack
     *
     * @return the value of relics.min_attack
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getMinAttack() {
        return minAttack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.min_attack
     *
     * @param minAttack the value for relics.min_attack
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMinAttack(Double minAttack) {
        this.minAttack = minAttack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.max_defense
     *
     * @return the value of relics.max_defense
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getMaxDefense() {
        return maxDefense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.max_defense
     *
     * @param maxDefense the value for relics.max_defense
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMaxDefense(Double maxDefense) {
        this.maxDefense = maxDefense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.min_defense
     *
     * @return the value of relics.min_defense
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getMinDefense() {
        return minDefense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.min_defense
     *
     * @param minDefense the value for relics.min_defense
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setMinDefense(Double minDefense) {
        this.minDefense = minDefense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.critical_strike_rate
     *
     * @return the value of relics.critical_strike_rate
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getCriticalStrikeRate() {
        return criticalStrikeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.critical_strike_rate
     *
     * @param criticalStrikeRate the value for relics.critical_strike_rate
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setCriticalStrikeRate(Double criticalStrikeRate) {
        this.criticalStrikeRate = criticalStrikeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.critical_strike_damage
     *
     * @return the value of relics.critical_strike_damage
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getCriticalStrikeDamage() {
        return criticalStrikeDamage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.critical_strike_damage
     *
     * @param criticalStrikeDamage the value for relics.critical_strike_damage
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setCriticalStrikeDamage(Double criticalStrikeDamage) {
        this.criticalStrikeDamage = criticalStrikeDamage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.proficients
     *
     * @return the value of relics.proficients
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getProficients() {
        return proficients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.proficients
     *
     * @param proficients the value for relics.proficients
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setProficients(Double proficients) {
        this.proficients = proficients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.charging_rate
     *
     * @return the value of relics.charging_rate
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public Double getChargingRate() {
        return chargingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.charging_rate
     *
     * @param chargingRate the value for relics.charging_rate
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setChargingRate(Double chargingRate) {
        this.chargingRate = chargingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relics.ext
     *
     * @return the value of relics.ext
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relics.ext
     *
     * @param ext the value for relics.ext
     *
     * @mbg.generated Thu Sep 14 10:24:21 CST 2023
     */
    public void setExt(String ext) {
        this.ext = ext;
    }
}