package com.example.uumemory.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RelicsParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public RelicsParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNull() {
            addCriterion("group_type is null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIsNotNull() {
            addCriterion("group_type is not null");
            return (Criteria) this;
        }

        public Criteria andGroupTypeEqualTo(String value) {
            addCriterion("group_type =", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotEqualTo(String value) {
            addCriterion("group_type <>", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThan(String value) {
            addCriterion("group_type >", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeGreaterThanOrEqualTo(String value) {
            addCriterion("group_type >=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThan(String value) {
            addCriterion("group_type <", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLessThanOrEqualTo(String value) {
            addCriterion("group_type <=", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeLike(String value) {
            addCriterion("group_type like", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotLike(String value) {
            addCriterion("group_type not like", value, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeIn(List<String> values) {
            addCriterion("group_type in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotIn(List<String> values) {
            addCriterion("group_type not in", values, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeBetween(String value1, String value2) {
            addCriterion("group_type between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andGroupTypeNotBetween(String value1, String value2) {
            addCriterion("group_type not between", value1, value2, "groupType");
            return (Criteria) this;
        }

        public Criteria andMainTypeIsNull() {
            addCriterion("main_type is null");
            return (Criteria) this;
        }

        public Criteria andMainTypeIsNotNull() {
            addCriterion("main_type is not null");
            return (Criteria) this;
        }

        public Criteria andMainTypeEqualTo(String value) {
            addCriterion("main_type =", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeNotEqualTo(String value) {
            addCriterion("main_type <>", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeGreaterThan(String value) {
            addCriterion("main_type >", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeGreaterThanOrEqualTo(String value) {
            addCriterion("main_type >=", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeLessThan(String value) {
            addCriterion("main_type <", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeLessThanOrEqualTo(String value) {
            addCriterion("main_type <=", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeLike(String value) {
            addCriterion("main_type like", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeNotLike(String value) {
            addCriterion("main_type not like", value, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeIn(List<String> values) {
            addCriterion("main_type in", values, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeNotIn(List<String> values) {
            addCriterion("main_type not in", values, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeBetween(String value1, String value2) {
            addCriterion("main_type between", value1, value2, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainTypeNotBetween(String value1, String value2) {
            addCriterion("main_type not between", value1, value2, "mainType");
            return (Criteria) this;
        }

        public Criteria andMainValueIsNull() {
            addCriterion("main_value is null");
            return (Criteria) this;
        }

        public Criteria andMainValueIsNotNull() {
            addCriterion("main_value is not null");
            return (Criteria) this;
        }

        public Criteria andMainValueEqualTo(Double value) {
            addCriterion("main_value =", value, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueNotEqualTo(Double value) {
            addCriterion("main_value <>", value, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueGreaterThan(Double value) {
            addCriterion("main_value >", value, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueGreaterThanOrEqualTo(Double value) {
            addCriterion("main_value >=", value, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueLessThan(Double value) {
            addCriterion("main_value <", value, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueLessThanOrEqualTo(Double value) {
            addCriterion("main_value <=", value, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueIn(List<Double> values) {
            addCriterion("main_value in", values, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueNotIn(List<Double> values) {
            addCriterion("main_value not in", values, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueBetween(Double value1, Double value2) {
            addCriterion("main_value between", value1, value2, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMainValueNotBetween(Double value1, Double value2) {
            addCriterion("main_value not between", value1, value2, "mainValue");
            return (Criteria) this;
        }

        public Criteria andMaxHealthIsNull() {
            addCriterion("max_health is null");
            return (Criteria) this;
        }

        public Criteria andMaxHealthIsNotNull() {
            addCriterion("max_health is not null");
            return (Criteria) this;
        }

        public Criteria andMaxHealthEqualTo(Double value) {
            addCriterion("max_health =", value, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthNotEqualTo(Double value) {
            addCriterion("max_health <>", value, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthGreaterThan(Double value) {
            addCriterion("max_health >", value, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthGreaterThanOrEqualTo(Double value) {
            addCriterion("max_health >=", value, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthLessThan(Double value) {
            addCriterion("max_health <", value, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthLessThanOrEqualTo(Double value) {
            addCriterion("max_health <=", value, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthIn(List<Double> values) {
            addCriterion("max_health in", values, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthNotIn(List<Double> values) {
            addCriterion("max_health not in", values, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthBetween(Double value1, Double value2) {
            addCriterion("max_health between", value1, value2, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMaxHealthNotBetween(Double value1, Double value2) {
            addCriterion("max_health not between", value1, value2, "maxHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthIsNull() {
            addCriterion("min_health is null");
            return (Criteria) this;
        }

        public Criteria andMinHealthIsNotNull() {
            addCriterion("min_health is not null");
            return (Criteria) this;
        }

        public Criteria andMinHealthEqualTo(Double value) {
            addCriterion("min_health =", value, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthNotEqualTo(Double value) {
            addCriterion("min_health <>", value, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthGreaterThan(Double value) {
            addCriterion("min_health >", value, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthGreaterThanOrEqualTo(Double value) {
            addCriterion("min_health >=", value, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthLessThan(Double value) {
            addCriterion("min_health <", value, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthLessThanOrEqualTo(Double value) {
            addCriterion("min_health <=", value, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthIn(List<Double> values) {
            addCriterion("min_health in", values, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthNotIn(List<Double> values) {
            addCriterion("min_health not in", values, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthBetween(Double value1, Double value2) {
            addCriterion("min_health between", value1, value2, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMinHealthNotBetween(Double value1, Double value2) {
            addCriterion("min_health not between", value1, value2, "minHealth");
            return (Criteria) this;
        }

        public Criteria andMaxAttackIsNull() {
            addCriterion("max_attack is null");
            return (Criteria) this;
        }

        public Criteria andMaxAttackIsNotNull() {
            addCriterion("max_attack is not null");
            return (Criteria) this;
        }

        public Criteria andMaxAttackEqualTo(Double value) {
            addCriterion("max_attack =", value, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackNotEqualTo(Double value) {
            addCriterion("max_attack <>", value, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackGreaterThan(Double value) {
            addCriterion("max_attack >", value, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackGreaterThanOrEqualTo(Double value) {
            addCriterion("max_attack >=", value, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackLessThan(Double value) {
            addCriterion("max_attack <", value, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackLessThanOrEqualTo(Double value) {
            addCriterion("max_attack <=", value, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackIn(List<Double> values) {
            addCriterion("max_attack in", values, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackNotIn(List<Double> values) {
            addCriterion("max_attack not in", values, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackBetween(Double value1, Double value2) {
            addCriterion("max_attack between", value1, value2, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMaxAttackNotBetween(Double value1, Double value2) {
            addCriterion("max_attack not between", value1, value2, "maxAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackIsNull() {
            addCriterion("min_attack is null");
            return (Criteria) this;
        }

        public Criteria andMinAttackIsNotNull() {
            addCriterion("min_attack is not null");
            return (Criteria) this;
        }

        public Criteria andMinAttackEqualTo(Double value) {
            addCriterion("min_attack =", value, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackNotEqualTo(Double value) {
            addCriterion("min_attack <>", value, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackGreaterThan(Double value) {
            addCriterion("min_attack >", value, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackGreaterThanOrEqualTo(Double value) {
            addCriterion("min_attack >=", value, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackLessThan(Double value) {
            addCriterion("min_attack <", value, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackLessThanOrEqualTo(Double value) {
            addCriterion("min_attack <=", value, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackIn(List<Double> values) {
            addCriterion("min_attack in", values, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackNotIn(List<Double> values) {
            addCriterion("min_attack not in", values, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackBetween(Double value1, Double value2) {
            addCriterion("min_attack between", value1, value2, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMinAttackNotBetween(Double value1, Double value2) {
            addCriterion("min_attack not between", value1, value2, "minAttack");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseIsNull() {
            addCriterion("max_defense is null");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseIsNotNull() {
            addCriterion("max_defense is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseEqualTo(Double value) {
            addCriterion("max_defense =", value, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseNotEqualTo(Double value) {
            addCriterion("max_defense <>", value, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseGreaterThan(Double value) {
            addCriterion("max_defense >", value, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseGreaterThanOrEqualTo(Double value) {
            addCriterion("max_defense >=", value, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseLessThan(Double value) {
            addCriterion("max_defense <", value, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseLessThanOrEqualTo(Double value) {
            addCriterion("max_defense <=", value, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseIn(List<Double> values) {
            addCriterion("max_defense in", values, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseNotIn(List<Double> values) {
            addCriterion("max_defense not in", values, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseBetween(Double value1, Double value2) {
            addCriterion("max_defense between", value1, value2, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMaxDefenseNotBetween(Double value1, Double value2) {
            addCriterion("max_defense not between", value1, value2, "maxDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseIsNull() {
            addCriterion("min_defense is null");
            return (Criteria) this;
        }

        public Criteria andMinDefenseIsNotNull() {
            addCriterion("min_defense is not null");
            return (Criteria) this;
        }

        public Criteria andMinDefenseEqualTo(Double value) {
            addCriterion("min_defense =", value, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseNotEqualTo(Double value) {
            addCriterion("min_defense <>", value, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseGreaterThan(Double value) {
            addCriterion("min_defense >", value, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseGreaterThanOrEqualTo(Double value) {
            addCriterion("min_defense >=", value, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseLessThan(Double value) {
            addCriterion("min_defense <", value, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseLessThanOrEqualTo(Double value) {
            addCriterion("min_defense <=", value, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseIn(List<Double> values) {
            addCriterion("min_defense in", values, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseNotIn(List<Double> values) {
            addCriterion("min_defense not in", values, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseBetween(Double value1, Double value2) {
            addCriterion("min_defense between", value1, value2, "minDefense");
            return (Criteria) this;
        }

        public Criteria andMinDefenseNotBetween(Double value1, Double value2) {
            addCriterion("min_defense not between", value1, value2, "minDefense");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateIsNull() {
            addCriterion("critical_strike_rate is null");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateIsNotNull() {
            addCriterion("critical_strike_rate is not null");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateEqualTo(Double value) {
            addCriterion("critical_strike_rate =", value, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateNotEqualTo(Double value) {
            addCriterion("critical_strike_rate <>", value, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateGreaterThan(Double value) {
            addCriterion("critical_strike_rate >", value, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateGreaterThanOrEqualTo(Double value) {
            addCriterion("critical_strike_rate >=", value, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateLessThan(Double value) {
            addCriterion("critical_strike_rate <", value, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateLessThanOrEqualTo(Double value) {
            addCriterion("critical_strike_rate <=", value, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateIn(List<Double> values) {
            addCriterion("critical_strike_rate in", values, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateNotIn(List<Double> values) {
            addCriterion("critical_strike_rate not in", values, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateBetween(Double value1, Double value2) {
            addCriterion("critical_strike_rate between", value1, value2, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeRateNotBetween(Double value1, Double value2) {
            addCriterion("critical_strike_rate not between", value1, value2, "criticalStrikeRate");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageIsNull() {
            addCriterion("critical_strike_damage is null");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageIsNotNull() {
            addCriterion("critical_strike_damage is not null");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageEqualTo(Double value) {
            addCriterion("critical_strike_damage =", value, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageNotEqualTo(Double value) {
            addCriterion("critical_strike_damage <>", value, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageGreaterThan(Double value) {
            addCriterion("critical_strike_damage >", value, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageGreaterThanOrEqualTo(Double value) {
            addCriterion("critical_strike_damage >=", value, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageLessThan(Double value) {
            addCriterion("critical_strike_damage <", value, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageLessThanOrEqualTo(Double value) {
            addCriterion("critical_strike_damage <=", value, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageIn(List<Double> values) {
            addCriterion("critical_strike_damage in", values, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageNotIn(List<Double> values) {
            addCriterion("critical_strike_damage not in", values, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageBetween(Double value1, Double value2) {
            addCriterion("critical_strike_damage between", value1, value2, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andCriticalStrikeDamageNotBetween(Double value1, Double value2) {
            addCriterion("critical_strike_damage not between", value1, value2, "criticalStrikeDamage");
            return (Criteria) this;
        }

        public Criteria andProficientsIsNull() {
            addCriterion("proficients is null");
            return (Criteria) this;
        }

        public Criteria andProficientsIsNotNull() {
            addCriterion("proficients is not null");
            return (Criteria) this;
        }

        public Criteria andProficientsEqualTo(Double value) {
            addCriterion("proficients =", value, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsNotEqualTo(Double value) {
            addCriterion("proficients <>", value, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsGreaterThan(Double value) {
            addCriterion("proficients >", value, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsGreaterThanOrEqualTo(Double value) {
            addCriterion("proficients >=", value, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsLessThan(Double value) {
            addCriterion("proficients <", value, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsLessThanOrEqualTo(Double value) {
            addCriterion("proficients <=", value, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsIn(List<Double> values) {
            addCriterion("proficients in", values, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsNotIn(List<Double> values) {
            addCriterion("proficients not in", values, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsBetween(Double value1, Double value2) {
            addCriterion("proficients between", value1, value2, "proficients");
            return (Criteria) this;
        }

        public Criteria andProficientsNotBetween(Double value1, Double value2) {
            addCriterion("proficients not between", value1, value2, "proficients");
            return (Criteria) this;
        }

        public Criteria andChargingRateIsNull() {
            addCriterion("charging_rate is null");
            return (Criteria) this;
        }

        public Criteria andChargingRateIsNotNull() {
            addCriterion("charging_rate is not null");
            return (Criteria) this;
        }

        public Criteria andChargingRateEqualTo(Double value) {
            addCriterion("charging_rate =", value, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateNotEqualTo(Double value) {
            addCriterion("charging_rate <>", value, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateGreaterThan(Double value) {
            addCriterion("charging_rate >", value, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateGreaterThanOrEqualTo(Double value) {
            addCriterion("charging_rate >=", value, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateLessThan(Double value) {
            addCriterion("charging_rate <", value, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateLessThanOrEqualTo(Double value) {
            addCriterion("charging_rate <=", value, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateIn(List<Double> values) {
            addCriterion("charging_rate in", values, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateNotIn(List<Double> values) {
            addCriterion("charging_rate not in", values, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateBetween(Double value1, Double value2) {
            addCriterion("charging_rate between", value1, value2, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andChargingRateNotBetween(Double value1, Double value2) {
            addCriterion("charging_rate not between", value1, value2, "chargingRate");
            return (Criteria) this;
        }

        public Criteria andExtIsNull() {
            addCriterion("ext is null");
            return (Criteria) this;
        }

        public Criteria andExtIsNotNull() {
            addCriterion("ext is not null");
            return (Criteria) this;
        }

        public Criteria andExtEqualTo(String value) {
            addCriterion("ext =", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtNotEqualTo(String value) {
            addCriterion("ext <>", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtGreaterThan(String value) {
            addCriterion("ext >", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtGreaterThanOrEqualTo(String value) {
            addCriterion("ext >=", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtLessThan(String value) {
            addCriterion("ext <", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtLessThanOrEqualTo(String value) {
            addCriterion("ext <=", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtLike(String value) {
            addCriterion("ext like", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtNotLike(String value) {
            addCriterion("ext not like", value, "ext");
            return (Criteria) this;
        }

        public Criteria andExtIn(List<String> values) {
            addCriterion("ext in", values, "ext");
            return (Criteria) this;
        }

        public Criteria andExtNotIn(List<String> values) {
            addCriterion("ext not in", values, "ext");
            return (Criteria) this;
        }

        public Criteria andExtBetween(String value1, String value2) {
            addCriterion("ext between", value1, value2, "ext");
            return (Criteria) this;
        }

        public Criteria andExtNotBetween(String value1, String value2) {
            addCriterion("ext not between", value1, value2, "ext");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relics
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 13 15:09:18 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table relics
     *
     * @mbg.generated Wed Sep 13 15:09:18 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}